### ISSUE TITLE
Doesn't compile against latest snapshot API version from Gerrit master

### ISSUE THREAD

**Issue by dpursehouse** [rinrinne/gerrit-rabbitmq-plugin#19]
1. Clone gerrit and check out the master branch
2. Build and install the plugin API to the local Maven repo with `buck build api_install`
3. Change API version to `2.12-SNAPSHOT` and build

Compilation fails:

```
Description	Resource	Path	Location	Type
The constructor File(Path, String) is undefined	Properties.java	/rabbitmq/src/main/java/com/googlesource/gerrit/plugins/rabbitmq	line 59	Java Problem
```

I can't fix this because the master branch already doesn't compile against the `2.11-SNAPSHOT` version, and putting the fix for this on the `api-2.11` branch will break the build for `2.11-SNAPSHOT`.

**Comment by rinrinne** [comment]
I cannot give positive support to unofficial releases.

If you want, I will open new branch named as `api-2.12`. Or you can have this in your forked repository only without PR. Which do you take?

**Comment by dpursehouse** [comment]
Well it depends how you define "unofficial release".

The typical development model for gerrit plugins is that the master branch is always kept buildable against the latest API built from gerrit's master branch, and there are separate branches for previous API versions. It's quite common that there is one latest fully released API and one or two versions still under development.  Currently the latest released is 2.10, and 2.11-SNAPSHOT and 2.12-SNAPSHOT are ongoing.

I don't want to maintain my own fork here on github.  If I fork it, I will do it on gerrit-review.googlesource.com which is where most of the other commonly used plugins are hosted.

**Comment by rinrinne** [comment]
I already understand what you mentioned. That's why I'm hosting this plugin in Github.

Gerrit in my community keeps official stable version.
My role is to supply this plugin to our gerrit. Unfortunately any activities against versions outside our scope are not evaluated.

So I cannot follow such development in Gerrit community. Possibly someone might help us if put this to gerrit-review, **but we don't want that.** Because we would have to keep an eye on backport. Maybe you could understand how strange such position is in Gerrit community.

Gerrit API library is now hosted at public repository. It means that anyone can develop gerrit plugin without dependency to official repository.

All you must know is that such public API makes us having the development style different with Gerrit community.

**Comment by dpursehouse** [comment]
From your comment I understand that you are developing this plugin on behalf of an employer, rather than as a private individual.

If that is correct I am surprised that it is being done with an anonymous account.  My employer, for example, has quite clear policies that open source contributions must be made with real names and affiliated to the company, i.e. using corporate email addresses in commits.   Also, there is a strict policy about legal approval of non-trivial contributions; for example I would not be allowed to contribute a plugin like this to open source without first following the correct process to ensure that the company's intellectual property is not leaked.

**Comment by rinrinne** [comment]
I have never said *I'm an employee.*

No legal issue about you activities like the above comment? I'm feeling strong pressure from you.

**Comment by dpursehouse** [comment]
> I have never said I'm an employee.

No, not explicitly, but it is strongly implied in your comment with words like "we", "our" and "us".

Are you saying that you are **not** acting on behalf of any company?

> No legal issue about you activities like the above comment?

Not as far as I know.  All my activity here is with my real name, and my affiliation is clearly stated in my profile.
